# Generated by Django 4.2.6 on 2023-10-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='image/')),
            ],
            options={
                'verbose_name': 'Taomlarni rasmi',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('name', models.CharField(max_length=50, verbose_name='Foydalanuvchi ismi')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('place', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'third'), (4, 'four'), (5, 'five'), (6, 'six'), (7, 'seven')], default=1)),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Joy buyurtma qilish',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='oshpazni ismi')),
                ('job', models.CharField(max_length=100, verbose_name='oshpazni turi')),
            ],
            options={
                'verbose_name': 'Oshpazlar haqida malumot',
            },
        ),
    ]
