# Generated by Django 4.2.5 on 2023-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='telefon raqam')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('location', models.CharField(max_length=255, verbose_name='manzil')),
                ('longitude', models.FloatField(verbose_name='manzil kodi')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'footer qismida malumotlar',
            },
        ),
    ]
