# Generated by Django 4.2.5 on 2023-11-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_email_created_at_email_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Email_mod',
        ),
    ]
