# Generated by Django 4.2.5 on 2023-11-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_email_email_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_mod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='email_mod',
            name='updated_at',
        ),
    ]
