# Generated by Django 4.2.5 on 2023-11-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_email_mod_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_mod',
        ),
    ]
