# Generated by Django 4.2.5 on 2023-11-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_email_mod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_mod',
        ),
    ]
