# Generated by Django 4.2.6 on 2023-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='teks nomi')),
                ('image', models.ImageField(upload_to='image/')),
                ('text', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Restoran haqida malumot',
            },
        ),
    ]
