# Generated by Django 4.2.6 on 2023-12-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.CharField(choices=[('drinks', 'DRINKS'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], default='dinner', max_length=10),
        ),
    ]
